export const RH_ROLES = {
  EMPLOYE: 'EMPLOYE',
  CHEF_HIERARCHIQUE: 'CHEF_HIERARCHIQUE',
  RH: 'RH',
  ADMIN: 'ADMIN'
} as const;

export type RhRole = typeof RH_ROLES[keyof typeof RH_ROLES];

export const ALL_RH_ROLES: RhRole[] = [
  RH_ROLES.EMPLOYE,
  RH_ROLES.CHEF_HIERARCHIQUE,
  RH_ROLES.RH,
  RH_ROLES.ADMIN
];

const ROLE_ALIASES: Record<string, RhRole> = {
  ADMINISTRATEUR: RH_ROLES.ADMIN,
  ADMINISTRATOR: RH_ROLES.ADMIN,
  ADMINS: RH_ROLES.ADMIN,
  EMPLOYEE: RH_ROLES.EMPLOYE,
  EMPLOYE: RH_ROLES.EMPLOYE,
  EMPLOYES: RH_ROLES.EMPLOYE,
  HR: RH_ROLES.RH,
  HUMAN_RESOURCES: RH_ROLES.RH,
  MANAGER: RH_ROLES.CHEF_HIERARCHIQUE,
  CHEF: RH_ROLES.CHEF_HIERARCHIQUE,
  CHEFS: RH_ROLES.CHEF_HIERARCHIQUE,
  CHEF_HIERARCHIQUE: RH_ROLES.CHEF_HIERARCHIQUE,
  CHEFS_HIERARCHIQUES: RH_ROLES.CHEF_HIERARCHIQUE,
  SUPERIEUR_HIERARCHIQUE: RH_ROLES.CHEF_HIERARCHIQUE,
  SUPERIEUR: RH_ROLES.CHEF_HIERARCHIQUE,
  RESPONSABLE: RH_ROLES.CHEF_HIERARCHIQUE,
  RESSOURCES_HUMAINES: RH_ROLES.RH,
  RESOURCE_HUMAN: RH_ROLES.RH,
  RESOURCES_HUMAINES: RH_ROLES.RH,
  GROUPE_ADMINS: RH_ROLES.ADMIN,
  GROUPE_CHEFS_HIERARCHIQUES: RH_ROLES.CHEF_HIERARCHIQUE,
  GROUPE_EMPLOYES: RH_ROLES.EMPLOYE,
  GROUPE_RH: RH_ROLES.RH
};

export function normalizeRhRole(role: string): string {
  const normalized = role
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toUpperCase()
    .replace(/^ROLE[_-]?/, '')
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  return ROLE_ALIASES[normalized] ?? normalized;
}
